// Bing News RSS search, constrained per category with a `site:` filter to
// the real outlets requested for that region — this is what actually
// determines "sources depending on region" rather than needing to guess
// 15+ individual publisher RSS feed URLs blind (several of those, checked
// during this session, don't have a confirmed public feed at all). Each
// category also pins a Bing market (`setmkt`) to steer its language.
//
// Links: Bing's RSS <link> is a click-tracking redirect
// (bing.com/news/apiclick.aspx?...&url=REAL_URL), which is what triggered
// the "this link may not be generated by Bing" interstitial reported after
// the first deploy — resolveLink below decodes and extracts the real `url`
// parameter instead of using the wrapper as-is.
export interface NewsItem {
  title: string;
  link: string;
}

export type NewsCategoryKey = "local" | "montreal" | "quebec" | "canada" | "us" | "europe" | "world";

export interface NewsCategory {
  key: NewsCategoryKey;
  items: NewsItem[];
}

export interface NewsDigest {
  categories: NewsCategory[];
  fetchedAt: string;
  errors: string[];
}

interface CategoryQuery {
  key: NewsCategoryKey;
  query: string;
  sites: string[];
  setmkt: string;
  limit: number;
}

const QC_SITES = ["journaldemontreal.com", "lapresse.ca", "tvanouvelles.ca", "ici.radio-canada.ca", "ctvnews.ca"];
const CANADA_SITES = [...QC_SITES, "theglobeandmail.com", "thestar.com", "globalnews.ca", "citynews.ca"];
const US_SITES = [
  "cnn.com",
  "abcnews.go.com",
  "msnbc.com",
  "foxnews.com",
  "cbsnews.com",
  "politico.com",
  "nytimes.com",
];
const EUROPE_SITES = ["bbc.com", "euronews.com", "lemonde.fr"];

function categoriesFor(): CategoryQuery[] {
  return [
    { key: "local", query: "Sainte-Agathe-des-Monts", sites: ["infodunordsainteagathe.ca"], setmkt: "fr-CA", limit: 1 },
    { key: "montreal", query: "Montréal", sites: QC_SITES, setmkt: "fr-CA", limit: 1 },
    { key: "quebec", query: "Québec", sites: QC_SITES, setmkt: "fr-CA", limit: 2 },
    { key: "canada", query: "Canada", sites: CANADA_SITES, setmkt: "en-CA", limit: 2 },
    { key: "us", query: "United States", sites: US_SITES, setmkt: "en-US", limit: 2 },
    { key: "europe", query: "Europe", sites: EUROPE_SITES, setmkt: "en-GB", limit: 2 },
    // No site filter: deliberately outside Canada/US/Europe, so this is
    // the closest a keyword can get to "the rest of the world" without a
    // paid, region-scoped news API.
    { key: "world", query: "international news Asia Africa Latin America Oceania", sites: [], setmkt: "en-US", limit: 2 },
  ];
}

function buildUrl(cat: CategoryQuery): string {
  const siteFilter = cat.sites.length > 0 ? `(${cat.sites.map((s) => `site:${s}`).join(" OR ")}) ` : "";
  return `https://www.bing.com/news/search?q=${encodeURIComponent(siteFilter + cat.query)}&format=RSS&setmkt=${cat.setmkt}`;
}

function decodeEntities(text: string): string {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">");
}

// Unwraps Bing's click-tracking redirect to the real article URL.
function resolveLink(rawLink: string): string {
  const decoded = decodeEntities(rawLink.trim());
  try {
    const url = new URL(decoded);
    if (url.hostname.endsWith("bing.com")) {
      const real = url.searchParams.get("url");
      if (real) return real;
    }
    return decoded;
  } catch {
    return decoded;
  }
}

function extractItems(xml: string, limit: number): NewsItem[] {
  const items: NewsItem[] = [];
  const itemRegex = /<item>([\s\S]*?)<\/item>/g;
  let match: RegExpExecArray | null;
  while ((match = itemRegex.exec(xml)) && items.length < limit) {
    const block = match[1];
    const titleMatch = block.match(/<title>(?:<!\[CDATA\[)?([\s\S]*?)(?:\]\]>)?<\/title>/);
    const linkMatch = block.match(/<link>([\s\S]*?)<\/link>/);
    if (titleMatch && linkMatch) {
      items.push({ title: decodeEntities(titleMatch[1].trim()), link: resolveLink(linkMatch[1]) });
    }
  }
  return items;
}

export async function getNewsDigest(): Promise<NewsDigest> {
  const cats = categoriesFor();
  const errors: string[] = [];
  const categories = await Promise.all(
    cats.map(async (cat): Promise<NewsCategory> => {
      try {
        const res = await fetch(buildUrl(cat), {
          headers: {
            "User-Agent":
              "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
          },
        });
        if (!res.ok) {
          errors.push(`${cat.key}: HTTP ${res.status}`);
          return { key: cat.key, items: [] };
        }
        const xml = await res.text();
        const items = extractItems(xml, cat.limit);
        if (items.length === 0) errors.push(`${cat.key}: 0 items parsed from a ${xml.length}-byte response`);
        return { key: cat.key, items };
      } catch (error) {
        errors.push(`${cat.key}: ${error instanceof Error ? error.message : String(error)}`);
        return { key: cat.key, items: [] };
      }
    })
  );
  return { categories, fetchedAt: new Date().toISOString(), errors };
}
