import { countryToCode } from "./country-flag";
import { normalizeRegionForCountry } from "./regions";
import { splitPhoneExtension } from "./phone-display";

// One representative IANA zone per province — Canada spans 6 zones, so
// country-level alone isn't enough. Saskatchewan doesn't observe DST
// (fixed CST, same as America/Regina); everywhere else does.
const CA_PROVINCE_TIMEZONE: Record<string, string> = {
  AB: "America/Edmonton",
  BC: "America/Vancouver",
  MB: "America/Winnipeg",
  NB: "America/Moncton",
  NL: "America/St_Johns",
  NS: "America/Halifax",
  NT: "America/Yellowknife",
  NU: "America/Iqaluit",
  ON: "America/Toronto",
  PE: "America/Halifax",
  QC: "America/Toronto",
  SK: "America/Regina",
  YT: "America/Whitehorse",
};

// One representative zone per state — most US states sit entirely in one
// zone; for the handful split across two (e.g. TX, TN, ND), this picks the
// zone covering the larger population.
const US_STATE_TIMEZONE: Record<string, string> = {
  AL: "America/Chicago",
  AK: "America/Anchorage",
  AZ: "America/Phoenix",
  AR: "America/Chicago",
  CA: "America/Los_Angeles",
  CO: "America/Denver",
  CT: "America/New_York",
  DE: "America/New_York",
  DC: "America/New_York",
  FL: "America/New_York",
  GA: "America/New_York",
  HI: "Pacific/Honolulu",
  ID: "America/Denver",
  IL: "America/Chicago",
  IN: "America/New_York",
  IA: "America/Chicago",
  KS: "America/Chicago",
  KY: "America/New_York",
  LA: "America/Chicago",
  ME: "America/New_York",
  MD: "America/New_York",
  MA: "America/New_York",
  MI: "America/New_York",
  MN: "America/Chicago",
  MS: "America/Chicago",
  MO: "America/Chicago",
  MT: "America/Denver",
  NE: "America/Chicago",
  NV: "America/Los_Angeles",
  NH: "America/New_York",
  NJ: "America/New_York",
  NM: "America/Denver",
  NY: "America/New_York",
  NC: "America/New_York",
  ND: "America/Chicago",
  OH: "America/New_York",
  OK: "America/Chicago",
  OR: "America/Los_Angeles",
  PA: "America/New_York",
  RI: "America/New_York",
  SC: "America/New_York",
  SD: "America/Chicago",
  TN: "America/Chicago",
  TX: "America/Chicago",
  UT: "America/Denver",
  VT: "America/New_York",
  VA: "America/New_York",
  WA: "America/Los_Angeles",
  WV: "America/New_York",
  WI: "America/Chicago",
  WY: "America/Denver",
  PR: "America/Puerto_Rico",
  GU: "Pacific/Guam",
  VI: "America/St_Thomas",
  AS: "Pacific/Pago_Pago",
  MP: "Pacific/Saipan",
};

const AU_STATE_TIMEZONE: Record<string, string> = {
  NSW: "Australia/Sydney",
  VIC: "Australia/Melbourne",
  QLD: "Australia/Brisbane",
  WA: "Australia/Perth",
  SA: "Australia/Adelaide",
  TAS: "Australia/Hobart",
  NT: "Australia/Darwin",
  ACT: "Australia/Sydney",
};

// Single representative zone for countries with (for our purposes) one
// effective timezone.
const COUNTRY_TIMEZONE: Record<string, string> = {
  FR: "Europe/Paris",
  AT: "Europe/Vienna",
  BE: "Europe/Brussels",
  BR: "America/Sao_Paulo",
  CH: "Europe/Zurich",
  CN: "Asia/Shanghai",
  DE: "Europe/Berlin",
  DK: "Europe/Copenhagen",
  ES: "Europe/Madrid",
  FI: "Europe/Helsinki",
  GB: "Europe/London",
  GR: "Europe/Athens",
  IE: "Europe/Dublin",
  IN: "Asia/Kolkata",
  IT: "Europe/Rome",
  JP: "Asia/Tokyo",
  MA: "Africa/Casablanca",
  MX: "America/Mexico_City",
  NL: "Europe/Amsterdam",
  NO: "Europe/Oslo",
  NZ: "Pacific/Auckland",
  PL: "Europe/Warsaw",
  PT: "Europe/Lisbon",
  SE: "Europe/Stockholm",
  SG: "Asia/Singapore",
  TN: "Africa/Tunis",
  ZA: "Africa/Johannesburg",
};

// Best-effort IANA timezone for a contact's country/state — used to show
// their local time, not for anything legal/billing-sensitive, so a
// single representative zone per state/province is an acceptable
// simplification even though a few states/provinces technically split
// across two zones.
export function getTimezoneForCountryState(
  countryNameOrCode: string | null | undefined,
  stateNameOrCode: string | null | undefined
): string | null {
  const code = countryToCode(countryNameOrCode);
  if (!code) return null;

  if (code === "CA" || code === "US" || code === "AU") {
    const region = normalizeRegionForCountry(countryNameOrCode, stateNameOrCode);
    const table = code === "CA" ? CA_PROVINCE_TIMEZONE : code === "US" ? US_STATE_TIMEZONE : AU_STATE_TIMEZONE;
    if (region && table[region]) return table[region];
    // No state on file — fall back to the most populous zone rather than
    // showing nothing.
    return code === "CA" ? "America/Toronto" : code === "US" ? "America/New_York" : "Australia/Sydney";
  }

  return COUNTRY_TIMEZONE[code] ?? null;
}

// NANP area code -> province, for contacts with a phone number but no
// address on file (common for a personal Google Contacts import — see
// google-contacts.ts). Omits the shared-867 territories (YT/NT/NU) rather
// than guess between them, and defaults the shared 902/782 to NS (much
// larger population than PE).
const CA_AREA_CODE_PROVINCE: Record<string, string> = {
  "403": "AB",
  "587": "AB",
  "780": "AB",
  "825": "AB",
  "236": "BC",
  "250": "BC",
  "604": "BC",
  "672": "BC",
  "778": "BC",
  "204": "MB",
  "431": "MB",
  "506": "NB",
  "709": "NL",
  "902": "NS",
  "782": "NS",
  "226": "ON",
  "249": "ON",
  "289": "ON",
  "343": "ON",
  "365": "ON",
  "416": "ON",
  "437": "ON",
  "519": "ON",
  "613": "ON",
  "647": "ON",
  "705": "ON",
  "807": "ON",
  "905": "ON",
  "367": "QC",
  "418": "QC",
  "438": "QC",
  "450": "QC",
  "514": "QC",
  "579": "QC",
  "581": "QC",
  "819": "QC",
  "873": "QC",
  "306": "SK",
  "639": "SK",
};

// Best-effort NANP area code -> state coverage for the US — not
// exhaustive (there are ~330 assigned codes and new overlay codes are
// added occasionally), but wide enough to cover every state at least
// once. Good enough for "show roughly the right local time," the same
// bar getTimezoneForCountryState's own state tables already hold to.
const US_AREA_CODE_STATE: Record<string, string> = {
  "907": "AK",
  "205": "AL",
  "251": "AL",
  "256": "AL",
  "334": "AL",
  "938": "AL",
  "479": "AR",
  "501": "AR",
  "870": "AR",
  "480": "AZ",
  "520": "AZ",
  "602": "AZ",
  "623": "AZ",
  "928": "AZ",
  "209": "CA",
  "213": "CA",
  "279": "CA",
  "310": "CA",
  "323": "CA",
  "341": "CA",
  "408": "CA",
  "415": "CA",
  "424": "CA",
  "442": "CA",
  "510": "CA",
  "530": "CA",
  "559": "CA",
  "562": "CA",
  "619": "CA",
  "626": "CA",
  "628": "CA",
  "650": "CA",
  "657": "CA",
  "661": "CA",
  "669": "CA",
  "707": "CA",
  "714": "CA",
  "747": "CA",
  "760": "CA",
  "805": "CA",
  "818": "CA",
  "820": "CA",
  "831": "CA",
  "858": "CA",
  "909": "CA",
  "916": "CA",
  "925": "CA",
  "949": "CA",
  "951": "CA",
  "303": "CO",
  "719": "CO",
  "720": "CO",
  "970": "CO",
  "203": "CT",
  "475": "CT",
  "860": "CT",
  "959": "CT",
  "202": "DC",
  "302": "DE",
  "305": "FL",
  "321": "FL",
  "352": "FL",
  "386": "FL",
  "407": "FL",
  "561": "FL",
  "727": "FL",
  "754": "FL",
  "772": "FL",
  "786": "FL",
  "813": "FL",
  "863": "FL",
  "904": "FL",
  "941": "FL",
  "954": "FL",
  "229": "GA",
  "404": "GA",
  "470": "GA",
  "478": "GA",
  "678": "GA",
  "706": "GA",
  "762": "GA",
  "770": "GA",
  "912": "GA",
  "808": "HI",
  "319": "IA",
  "515": "IA",
  "563": "IA",
  "641": "IA",
  "712": "IA",
  "208": "ID",
  "986": "ID",
  "217": "IL",
  "224": "IL",
  "309": "IL",
  "312": "IL",
  "331": "IL",
  "618": "IL",
  "630": "IL",
  "708": "IL",
  "773": "IL",
  "779": "IL",
  "815": "IL",
  "847": "IL",
  "872": "IL",
  "219": "IN",
  "260": "IN",
  "317": "IN",
  "463": "IN",
  "574": "IN",
  "765": "IN",
  "812": "IN",
  "930": "IN",
  "316": "KS",
  "620": "KS",
  "785": "KS",
  "913": "KS",
  "270": "KY",
  "364": "KY",
  "502": "KY",
  "606": "KY",
  "859": "KY",
  "225": "LA",
  "318": "LA",
  "337": "LA",
  "504": "LA",
  "985": "LA",
  "339": "MA",
  "351": "MA",
  "413": "MA",
  "508": "MA",
  "617": "MA",
  "774": "MA",
  "781": "MA",
  "857": "MA",
  "978": "MA",
  "240": "MD",
  "301": "MD",
  "410": "MD",
  "443": "MD",
  "667": "MD",
  "207": "ME",
  "231": "MI",
  "248": "MI",
  "269": "MI",
  "313": "MI",
  "517": "MI",
  "586": "MI",
  "616": "MI",
  "734": "MI",
  "810": "MI",
  "906": "MI",
  "947": "MI",
  "989": "MI",
  "218": "MN",
  "320": "MN",
  "507": "MN",
  "612": "MN",
  "651": "MN",
  "763": "MN",
  "952": "MN",
  "314": "MO",
  "417": "MO",
  "573": "MO",
  "636": "MO",
  "660": "MO",
  "816": "MO",
  "975": "MO",
  "228": "MS",
  "601": "MS",
  "662": "MS",
  "769": "MS",
  "406": "MT",
  "252": "NC",
  "336": "NC",
  "704": "NC",
  "743": "NC",
  "828": "NC",
  "910": "NC",
  "919": "NC",
  "980": "NC",
  "984": "NC",
  "701": "ND",
  "308": "NE",
  "402": "NE",
  "531": "NE",
  "603": "NH",
  "201": "NJ",
  "551": "NJ",
  "609": "NJ",
  "640": "NJ",
  "732": "NJ",
  "848": "NJ",
  "856": "NJ",
  "862": "NJ",
  "908": "NJ",
  "973": "NJ",
  "505": "NM",
  "575": "NM",
  "702": "NV",
  "725": "NV",
  "775": "NV",
  "212": "NY",
  "315": "NY",
  "332": "NY",
  "347": "NY",
  "516": "NY",
  "518": "NY",
  "585": "NY",
  "607": "NY",
  "631": "NY",
  "646": "NY",
  "680": "NY",
  "716": "NY",
  "718": "NY",
  "838": "NY",
  "845": "NY",
  "914": "NY",
  "917": "NY",
  "929": "NY",
  "934": "NY",
  "216": "OH",
  "220": "OH",
  "234": "OH",
  "330": "OH",
  "380": "OH",
  "419": "OH",
  "440": "OH",
  "513": "OH",
  "567": "OH",
  "614": "OH",
  "740": "OH",
  "937": "OH",
  "405": "OK",
  "539": "OK",
  "580": "OK",
  "918": "OK",
  "458": "OR",
  "503": "OR",
  "541": "OR",
  "971": "OR",
  "215": "PA",
  "223": "PA",
  "267": "PA",
  "272": "PA",
  "412": "PA",
  "445": "PA",
  "484": "PA",
  "570": "PA",
  "610": "PA",
  "717": "PA",
  "724": "PA",
  "814": "PA",
  "878": "PA",
  "401": "RI",
  "803": "SC",
  "839": "SC",
  "843": "SC",
  "854": "SC",
  "864": "SC",
  "605": "SD",
  "423": "TN",
  "615": "TN",
  "629": "TN",
  "731": "TN",
  "865": "TN",
  "901": "TN",
  "931": "TN",
  "214": "TX",
  "254": "TX",
  "281": "TX",
  "325": "TX",
  "346": "TX",
  "361": "TX",
  "409": "TX",
  "430": "TX",
  "432": "TX",
  "469": "TX",
  "512": "TX",
  "682": "TX",
  "713": "TX",
  "726": "TX",
  "737": "TX",
  "806": "TX",
  "817": "TX",
  "830": "TX",
  "832": "TX",
  "903": "TX",
  "936": "TX",
  "940": "TX",
  "956": "TX",
  "972": "TX",
  "979": "TX",
  "385": "UT",
  "435": "UT",
  "801": "UT",
  "276": "VA",
  "434": "VA",
  "540": "VA",
  "571": "VA",
  "703": "VA",
  "757": "VA",
  "804": "VA",
  "206": "WA",
  "253": "WA",
  "360": "WA",
  "425": "WA",
  "509": "WA",
  "564": "WA",
  "262": "WI",
  "274": "WI",
  "414": "WI",
  "534": "WI",
  "608": "WI",
  "715": "WI",
  "920": "WI",
  "304": "WV",
  "681": "WV",
  "307": "WY",
};

// A contact's timeZone is otherwise derived from country/state — this is
// the fallback for a phone-only contact with no address on file (again,
// the common case for a personal Google Contacts import): the area code
// alone is often the only regional signal available. Works regardless of
// whether the number carries a leading "+1"/"1" or not — the area code is
// always the first 3 digits of the last 10.
export function getTimezoneFromAreaCode(phone: string | null | undefined): string | null {
  if (!phone) return null;
  const { number } = splitPhoneExtension(phone);
  const digits = number.replace(/\D/g, "");
  if (digits.length < 10) return null;
  const areaCode = digits.slice(-10, -7);
  const province = CA_AREA_CODE_PROVINCE[areaCode];
  if (province) return CA_PROVINCE_TIMEZONE[province] ?? null;
  const state = US_AREA_CODE_STATE[areaCode];
  if (state) return US_STATE_TIMEZONE[state] ?? null;
  return null;
}

// "UTC-5" / "UTC+5:30" — derived from the zone's *current* offset (so it
// already reflects DST), not a static table.
export function utcOffsetLabel(timeZone: string, at: Date = new Date()): string {
  const parts = new Intl.DateTimeFormat("en-US", { timeZone, timeZoneName: "shortOffset" }).formatToParts(at);
  const tzPart = parts.find((p) => p.type === "timeZoneName")?.value ?? "GMT+0";
  return tzPart.replace("GMT", "UTC");
}
