-- AlterEnum
ALTER TYPE "ProjectType" ADD VALUE 'STORE';
ALTER TYPE "ProjectType" ADD VALUE 'CRM_CUSTOMIZATION';
ALTER TYPE "ProjectType" ADD VALUE 'AUTOMATION';
ALTER TYPE "ProjectType" ADD VALUE 'EMAIL_MARKETING';
ALTER TYPE "ProjectType" ADD VALUE 'SMS_MARKETING';
ALTER TYPE "ProjectType" ADD VALUE 'TRAINING';
ALTER TYPE "ProjectType" ADD VALUE 'AFFILIATE_MARKETING';
